from fastapi import FastAPI


from app.firestore import Firestore
from app.ai import ChatEngine

app = FastAPI()

@app.post('/chat/{chat_id}')
def get_response(chat_id: str):
    '''Sending a response generated by chatbot'''
    firestore = Firestore(chat_id=chat_id)
    
    last_messages = firestore.last_n_messages(20)
    summary = firestore.get_summary()
    messages_count = firestore.messages_count()

    if messages_count % 20 == 0:
        new_summary = ChatEngine().summarize(new_messages=last_messages, prev_summary=summary)
        firestore.update_summary(str(new_summary.text))

    response = ChatEngine().generate_response(
        query=last_messages[0],
        summary=summary,
        last_messages=last_messages
    )

    firestore.send_message(str(response))

@app.delete('/chat/{chat_id}/delete_history')
async def delete_history(chat_id: str):
    firestore = Firestore(chat_id=chat_id)
    await recursive_delete(firestore.messages, firestore.messages_count())

async def recursive_delete(coll_ref, batch_size):
    messages = firestore.messages
    docs = messages.limit(batch_size).stream()
    deleted = 0

    async for doc in docs:
        await doc.reference.delete()
        deleted = deleted + 1

    if deleted >= batch_size:
        return recursive_delete(coll_ref, batch_size)

firestore = Firestore("uQsBAQ3iNYRWdE5MdAgm6gAaQi13")
print(firestore.last_n_messages(2))